// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxuirifppymbfinwxbkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dWlyaWZwcHltYmZpbnd4YmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjgyOTUsImV4cCI6MjA2MDYwNDI5NX0.n73JnFgsQde9IFCcPoRe95JIpm2wJwvp-H-543Yt_Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);